#! /usr/bin/awk -f

# will produce a mgf file from a mgf file but with
# the highest intensity peak in a spectrum deleted

/^BEGIN IONS$/    {max = 0}
/^[^0-9]/         {print $0}
/^[0-9]*\.[0-9]*/ {if ($2>max) {max=$2} else {print $0}}
/^END IONS$/      {print ""}
